
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benza.fullname" . }}-backend-env
type: Opaque
stringData:
  ADMIN_PASS: {{ .Values.backend.adminPassword | default (randAlphaNum 16) | quote }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | default (randAlphaNum 48) | quote }}