apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benza.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "benza.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      labels:
        {{- include "benza.selectorLabels" . | nindent 8 }}
        app: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000