{{- if .Values.storage.persistance }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "benza.fullname" . }}-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
{{- end }}