apiVersion: v1
kind: Service
metadata:
  name: {{ include "benza.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "benza.selectorLabels" . | nindent 4 }}
    app: frontend
