name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose

      # - name: Rush Run Units Test (Backend)
      #   run: | 
      #     cd packages/backend 
      #     node ../../common/scripts/install-run-rushx.js test --ci
      #     cd ../../

      # - name: Run e2e Test (Backend)
      #   run: | 
      #     cd packages/backend 
      #     npm run test:e2e
      #     cd ../../

      - name: Extract version or set default
        id: get_version
        shell: bash
        run: |
          VERSION=$(git describe --tags --abbrev=0 --always)
          if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta) ]]; then
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gas-station-simulator-frontend:${{ steps.get_version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gas-station-simulator-backend:${{ steps.get_version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}